services:

  web:
    build: .
    container_name: flask-web

    ports:
      - "5000:5000"

    environment:
      DB_HOST: postgres
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: password

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    container_name: postgres-db

    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
